# Generated by Django 5.1.3 on 2024-11-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_name',
            field=models.CharField(blank=True, help_text='Please enter your first name.', max_length=255),
        ),
    ]
